name: demo_upload-download-artifact
on: workflow_dispatch


jobs:
    upload:
        name: upload
        runs-on: ubuntu-latest
        steps:
            - name: create file
              run: echo "Hello world" > artifact.txt
            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: artifact
                path: artifact.txt

    download:
        needs: upload
        name: download
        runs-on: ubuntu-latest
        steps:
            - name: download artifact
              uses: actions/download-artifact@v3
              with:
                name: artifact
            - name: read file
              run: cat artifact.txt