name: Auto Branch Creation

on:
  issues:
    types:
      - assigned

jobs:
  auto-branch-creation:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create branch
        run: |
          BRANCH_NAME="feature/issue-${{ github.event.issue.number }}"
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME
