name: Feature Tests

on:
  pull_request:
    branches:
      - 'develop'
    types:
      - opened

jobs:
  feature-tests:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'feature/')
    
    strategy:
      matrix:
        node-version: [16, 14]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm run test

      - name: Run tests coverage
        run: npm run test:coverage
