name: Workflow Run
on: 
    workflow_run:
        types: [completed]

jobs:
    workflow_run_job:
        runs-on: ubuntu-latest
        steps:
            - name: workflow_run
              if: github.event.workflow_run.status == 'completed'
              run : echo "Worlflow is Completed" 