name: Issue Opened
on: 
    issues:
        types: [opened]

jobs:
    issue_opened:
        runs-on: ubuntu-latest
        steps:
            - name: Issue Opened
              run : echo "Issue Opened" 