name: Workflow Run
on: 
    workflow_run:
        workflows: ["Pull Requests"]
        types: [completed]

jobs:
    workflow_run_job:
        runs-on: ubuntu-latest
        steps:
            - name: workflow_run
              run : echo "PR is completed" 